// This file is generated automatically
export const tinyRegular: string;
export const marginTop10: string;
export const marginTop20: string;
export const marginTop32: string;
export const marginTop56: string;
export const input: string;
export const inputWrapper: string;
export const icon: string;
export const leftIconPos: string;
export const rightIconPos: string;
export const err: string;
export const success: string;
export const textField: string;
export const leftIcon: string;
export const rightIcon: string;
export const disabledTextField: string;
export const message: string;
export const messageIcon: string;
